version: 1
builder:
  configs:
    - documentation_targets: [SwiftNPSDataModels, SwiftNPSData, SwiftNPSSpeciesModels, SwiftNPSSpecies, SwiftNPSUnitsModels, SwiftNPSUnits, SwiftNPSVisitationModels, SwiftNPSVisitation]
      platform: ios
